---
name: Docs
on:
  pull_request:
    branches:
      - master

jobs:
  gen_docs:
    name: Generate docs and changelog
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout changes
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set MERGE_SHA in env
        run: |
          export SHA=$(git log --pretty=format:'%p' -1 | tr -d '[:space:]')
          echo "##[set-env name=MERGE_SHA;]$SHA"
          echo "$SHA"

      - name: Retrieve changelog from Github PR body
        run:
          sudo apt-get install jq;
          cat ${{ github.event_path }} | jq -r .pull_request.body > /tmp/body;
          cat /tmp/body | sed -ne '/^## Changelog/,$ p' > /tmp/changelog;

          if [[ -z $(cat /tmp/changelog) ]]; then
              echo "[Error] empty changelog"; exit 1;
          fi

      - name: Format changelog
        run:
          cat /tmp/changelog | sed '/<!--/,/-->/d' |
          awk '!NF {if (++n <= 1) print; next}; {n=0;print}' |
          sed -e '/./,$!d' -e :a -e '/^\n*$/{$d;N;ba' -e '}'
          > /tmp/changelog_formated;

          cat /tmp/changelog_formated

      - name: Upload changelog artifact
        uses: actions/upload-artifact@v1
        with:
          name: changelog-${{ env.MERGE_SHA }}
          path: /tmp/changelog_formated
