---
name: Release
on:
  push:
    branches:
      - master

jobs:
  tag_branch:
    name: Create Github release
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout changes
        uses: actions/checkout@v2
        with:
          fetch-depth: 5

      - name: Create tmp config file
        run: |
           printf "module.exports = {
               plugins: [
                   '@semantic-release/commit-analyzer',
                   '@semantic-release/release-notes-generator',
                   '@semantic-release/github',
                   ['@semantic-release/changelog', {
                       'changelogFile': 'CHANGELOG.md',
                       'changelogTitle': 'Global Changelog',
                   }],
                   ['@semantic-release/git', {
                      'assets': ['CHANGELOG.md'],
                      'message': 'docs: add generated docs and changelog'
                   }],
               ],
            };" > .releaserc.js

      - name: Generate Semantic Release version
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          dry_run: true
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Display Changelog and version
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo ${{ steps.semantic.outputs.new_release_version }}
          # cat CHANGELOG.md

      # - name: Commit docs and changelog
      #   run: |
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     git add CHANGELOG.md
      #     git commit -m "docs: add generated docs and changelog"

      # - name: Push docs and changelog
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     uses: stefanzweifel/git-auto-commit-action@v4.1.0

      - name: Generate Semantic Release version
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: GitHub Action
          GIT_AUTHOR_EMAIL: action@github.com
          GIT_COMMITTER_NAME: GitHub Action
          GIT_COMMITTER_EMAIL: action@github.com
