---
name: Release
on:
  push:
    branches:
      - master

jobs:
  tag_branch:
    name: Publish version tag
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout changes
        uses: actions/checkout@v2
        with:
          fetch-depth: 5

      - name: Create tmp config file
        run: |
           printf "module.exports = {
               plugins: [
                   '@semantic-release/commit-analyzer',
                   '@semantic-release/release-notes-generator',
                   '@semantic-release/github',
                   ['@semantic-release/changelog', {
                       'changelogFile': 'CHANGELOG.md',
                       'changelogTitle': 'Global Changelog',
                   }],
               ],
            };" > .releaserc.js

      - name: Generate Semantic Release version
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          extra_plugins: |
            @semantic-release/changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cat changelog
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
            cat CHANGELOG.md
            echo ${{ steps.semantic.outputs.new_release_version }}

      - name: Push docs and changelog
        uses: github-actions-x/commit@v2.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: master
          commit-message: 'docs: generate docs and changelog'
          files: CHANGELOG.md
