name: SSH on runner
on:
  workflow_dispatch:
    inputs:
      os:
        description: "Operating System"
        required: true
        default: ubuntu-latest
        type: choice
        options:
          - ubuntu-latest
          - macos-latest
          - windows-latest
      mod:
        description: "Install Go"
        required: true
        default: true
        type: boolean

jobs:
  setup-ssh:
    name: Setup runner and open SSH endpoint
    runs-on: ${{ github.event.inputs.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup go
        uses: actions/setup-go@v5

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
