---
name: Generate changelog
on:
  pull_request:

jobs:
  publish:
    name: Generate changelog
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout changes
        uses: actions/checkout@v2

      - name: Set PR_BODY
        run: |
            sudo apt-get install jq
            export RES=$(cat ${{ github.event_path }} | jq .pull_request.body)
            echo "##[set-env name=PR_BODY;]$RES"
- name: Display PR_BODY
        run: echo "$PR_BODY"
