---
name: Generate changelog
on:
  pull_request:

jobs:
  publish:
    name: Generate changelog
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout changes
        uses: actions/checkout@v2

      - name: Cat github.event_path
        run: cat ${{ github.event_path }}
